# Generated by Django 3.2.4 on 2024-10-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_city_country_finanzas_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.country'),
        ),
        migrations.AddField(
            model_name='property',
            name='num_bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='num_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='project_category',
            field=models.CharField(choices=[('social', 'Interés Social'), ('luxury', 'Luxury'), ('premium', 'Premium')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='project_type',
            field=models.CharField(choices=[('pozo', 'Pozo'), ('no_pozo', 'No Pozo')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='chat.province'),
        ),
        migrations.AddField(
            model_name='property',
            name='residence_type',
            field=models.CharField(choices=[('familiar', 'Familiar'), ('unipersonal', 'Unipersonal'), ('universitaria', 'Universitaria')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
